services:
  postgres:
    image: postgres:15-alpine
    container_name: fcstask-db
    environment:
      POSTGRES_USER: fcstask
      POSTGRES_PASSWORD: fcstask_password
      POSTGRES_DB: fcstask-monitor-bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fcstask-app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
